spring.application.name=interview-schedular

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/interview-schedular?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ashishkumar
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Server Configuration
server.port=8081

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Thread Pool Configuration
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=15
spring.task.execution.pool.queue-capacity=500
spring.task.execution.thread-name-prefix=bulk-send-task-

# WhatsApp Cloud API
whatsapp.provider=meta
whatsapp.meta.base-url=https://graph.facebook.com
whatsapp.meta.api-version=v23.0
whatsapp.meta.phone-number-id=1225462177297559
whatsapp.meta.business-account-id=3128293134227030
whatsapp.meta.sender-number=7010020451

#Token
whatsapp.meta.access-token=EAAZATu1NdUKwBRlHKszC2hOtXJCRGVAB9wfhwESWIkcZAkZCle36yUGnzTzxzfJgjXyHVXgq8LbnLG4Xz8Acc2Q7ywHD9I8ZCke7uzUlcLr2sTf79ZBiZACvNakvRBYmesQjw2FQYBFXTQDjkx6XZBXtSPXh3BNJoc7UYZAKq5R4SgeCfHvhwsg86tTL7PnP1AZDZD
whatsapp.meta.verify-token=tvmFirstSecretVerifyToken

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method

# SMTP Mail Server Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ashishstarrd@gmail.com
spring.mail.password=rqhfefwlbrpdrzph
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true